CREATE DATABASE EEUMGOREE;

CREATE TABLE MEMBER (
	MEMBER_ID  BIGINT PRIMARY KEY AUTO_INCREMENT,
	ID         VARCHAR(255) NOT NULL,
	PASSWORD   VARCHAR(255) NOT NULL,
	NAME       VARCHAR(255) NOT NULL,
	PRIVATE_ID VARCHAR(255) NOT NULL,
	HP         VARCHAR(255) NOT NULL,	
	EMAIL      VARCHAR(255) NOT NULL,
	ENROLL_DT  TIMESTAMP
)

CREATE TABLE REGITPRODUCT(
	PRODUCT_CD    BIGINT PRIMARY KEY,
	PRODUCT_NAME  VARCHAR(255) NOT NULL,
	PRODUCT_DESC  VARCHAR(2000) NOT NULL,
	PRICE         INT NOT NULL,
	PRODUCT_IMG   VARCHAR(255) NOT NULL,
	CATEGORY      VARCHAR(255) NOT NULL,
	SUBCATEGORY   VARCHAR(255) NOT NULL,
	CONDITION     VARCHAR(30) NOT NULL,
	REGIT_DT      TIMESTAMP,
)

CREATE TABLE ORDER (
	PRODUCT_CD BIGINT,
	MEMBER_ID  BIGINT,
	FOREIGN KEY(PRODUCT_CD) REFERENCES REGITPRODUCT(PRODUCT_CD),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	
)