CREATE DATABASE IF NOT EXISTS MODUDEAL;

USE MODUDEAL;

CREATE TABLE ADMIN (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE MEMBERS (
    MEMBER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL, 
    NAME VARCHAR(100) NOT NULL,
    BIRTHDATE DATE,
    HP VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    ADDRESS_ZIPCODE VARCHAR(10) NOT NULL,
    ADDRESS_ROAD VARCHAR(255),
    ADDRESS_JIBUN VARCHAR(255),
    ADDRESS_NAMUJI VARCHAR(255),
    SMS_RECV_AGREE ENUM('Y', 'N') DEFAULT 'Y',
    EMAIL_RECV_AGREE ENUM('Y', 'N') DEFAULT 'Y',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    IMG_URL VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    QTY INT,
    PRICE DECIMAL(10, 2),
    PRODUCT_CATEGORY VARCHAR(50) NOT NULL,
    MEMBER_ID INT,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

CREATE TABLE CHATS (
    CHAT_ID INT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ID INT NOT NULL,
    RECEIVER_ID INT NOT NULL,
    MESSAGE TEXT NOT NULL,
    SEND_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ID) REFERENCES MEMBERS(MEMBER_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES MEMBERS(MEMBER_ID)
);