CREATE DATABASE MODUDEAL;

USE MODUDEAL;

CREATE TABLE ADMIN (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE MODUDEAL_MEMBER (
    MEMBER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL, 
    NAME VARCHAR(100) NOT NULL,
    BIRTHDATE DATE,
    HP VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    ADDRESS_ZIPCODE VARCHAR(10) NOT NULL,
    ADDRESS_ROAD VARCHAR(255),
    ADDRESS_JIBUN VARCHAR(255),
    ADDRESS_NAMUJI VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    QTY INT,
    PRICE DECIMAL(10, 2),
    PRODUCT_CATEGORY VARCHAR(50) NOT NULL,
    MEMBER_ID INT,
    FOREIGN KEY (MEMBER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID)
);

CREATE TABLE PRODUCT_IMG (
    IMG_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    IMG_URL VARCHAR(255) NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE CHAT (
    CHAT_ID INT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ID INT NOT NULL,
    RECEIVER_ID INT NOT NULL,
    MESSAGE TEXT NOT NULL,
    SEND_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID)
);

CREATE TABLE CART (
    CART_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QTY INT NOT NULL,
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE WISHLIST (
    WISHLIST_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_IMG_URL VARCHAR(255),
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE NOTICE (
    NOTICE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

CREATE TABLE QNA (
    QNA_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT,
    QUESTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ANSWER_DATE TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE QUESTION_BOARD (
    QUESTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT,
    QUESTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ANSWER_DATE TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID)
);

CREATE TABLE SELLER_PRODUCT (
    SELLER_PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_IMG_URL VARCHAR(255),
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE BUYER_PRODUCT (
    BUYER_PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_IMG_URL VARCHAR(255),
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE COMPLETED_TRADE(
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    BUYER_ID INT NOT NULL,
    SELLER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BUYER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID),
    FOREIGN KEY (SELLER_ID) REFERENCES MODUDEAL_MEMBER(MEMBER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE PRODUCT_LIKES (
    LIKE_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    LIKES_COUNT INT DEFAULT 0,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);