CREATE DATABASE EEUMGOREE;

USE EEUMGREE;

CREATE TABLE MEMBER (

	ID   					VARCHAR(255),
	PW		 				VARCHAR(255),
	NAME					VARCHAR(255),
	RESIDENT_NUMBER   		VARCHAR(255),
	PHONE_NUMBER			VARCHAR(255),
	EMAIL					VARCHAR(255),
	CREATED_AT				DATE,
)