CREATE DATABASE EEUMGOREE;

CREATE TABLE USER (
	MEMBER_ID  BIGINT PRIMARY KEY AUTO_INCREMENT,
	ID         VARCHAR(255),
	PASSWORD   VARCHAR(255),
	NAME       VARCHAR(255),
	PRIVATE_ID VARCHAR(255),
	HP         VARCHAR(255),	
	EMAIL      VARCHAR(255),
	ENROLL_DT  TIMESTAMP
)

CREATE TABLE REGITPRODUCT(
	PRODUCT_CD    BIGINT,
	PRODUCT_NAME  VARCHAR(255),
	PRODUCT_DESC  VARCHAR(2000),
	PRICE         INT,
	PRODUCT_IMG   VARCHAR(255) ,
	CATEGORY      VARCHAR(255),
	SUBCATEGORY   VARCHAR(255)
)

