CREATE DATABASE BMS;
USE BMS;

CREATE TABLE ADMIN(
    ADMIN_ID 	VARCHAR(255) PRIMARY KEY,
	PASSWD 		VARCHAR(255),				# NOT NULL
	JOIN_DT 	TIMESTAMP 	 				# NOT NULL
);	

INSERT INTO ADMIN VALUES ('bmsadmin' , 'P@ssw0rd' , NOW());


CREATE TABLE MEMBER(
    MEMBER_ID 		VARCHAR(255) PRIMARY KEY,
	MEMBER_NM 		VARCHAR(255),				# NOT NULL
    PASSWD 			VARCHAR(255),				# NOT NULL UNIQUE
	SEX 			CHAR(1),					# NOT NULL
	DATE_BIRTH 		CHAR(10),					# NOT NULL
	HP 				VARCHAR(255), 				# NOT NULL
	SMSSTS_YN 		CHAR(1),					# NOT NULL
	EMAIL 			VARCHAR(255),				# NOT NULL
	EMAILSTS_YN 	CHAR(1),					# NOT NULL
	ZIPCODE 		VARCHAR(255),
	ROAD_ADDRESS 	VARCHAR(255),
	JIBUN_ADDRESS 	VARCHAR(255),
	NAMUJI_ADDRESS 	VARCHAR(255),
	POINT			INT,						# NOT NULL
	JOIN_DT 		TIMESTAMP					# NOT NULL
);


CREATE TABLE BOOK(
    BOOK_ID 		  BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_NM 		  VARCHAR(255),						# NOT NULL
    WRITER 			  VARCHAR(255),						# NOT NULL	
	PRICE 			  INT,								# NOT NULL				
	DISCOUNT_RATE 	  INT,								# NOT NULL
	STOCK			  INT,								# NOT NULL
	PUBLISHER 		  VARCHAR(255),						# NOT NULL
	SORT 			  VARCHAR(255),						# NOT NULL
	POINT 			  INT,								# NOT NULL		
	PUBLISHED_DT 	  TIMESTAMP,						# NOT NULL
	TOTAL_PAGE 		  INT,								# NOT NULL
	ISBN 			  VARCHAR(255),						# NOT NULL
	DELIVERY_PRICE 	  INT,								# NOT NULL
	PART 			  VARCHAR(255),						# NOT NULL
	WRITER_INTRO 	  TEXT,
	CONTENTS_ORDER 	  TEXT,
	INTRO 			  TEXT,
	PUBLISHER_COMMENT TEXT,
	RECOMMENDATION 	  TEXT,
	BOOK_IMG_NM	  	  VARCHAR(255),						# NOT NULL UNIQUE
	ENROLL_DT 		  TIMESTAMP							# NOT NULL
);


CREATE TABLE `ORDER`(
	ORDER_ID 			BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID 			VARCHAR(255),							# NOT NULL			
    BOOK_ID 			BIGINT,							# NOT NULL
	ORDER_BOOK_QTY 		INT,							# NOT NULL
	PAYMENT_AMT			INT,							# NOT NULL
    ORDERER_NM 			VARCHAR(255),					# NOT NULL
    ORDERER_HP 			VARCHAR(255),					# NOT NULL
	RECEIVER_NM 		VARCHAR(255),					# NOT NULL
	RECEIVER_HP 		VARCHAR(255),					# NOT NULL
	ZIPCODE 			VARCHAR(255),					# NOT NULL
	ROAD_ADDRESS 		VARCHAR(255),					# NOT NULL
	JIBUN_ADDRESS 		VARCHAR(255),					# NOT NULL
	NAMUJI_ADDRESS 		VARCHAR(255),					# NOT NULL
    DELIVERY_METHOD 	VARCHAR(255),					# NOT NULL
    DELIVERY_MESSAGE 	VARCHAR(255),
    DELIVERY_STATUS 	VARCHAR(255),					# NOT NULL
	GIFT_WRAPPING 		CHAR(1),						# NOT NULL
	PAY_METHOD 			VARCHAR(255),
	PAY_ORDERER_HP 		VARCHAR(255), 
	CARD_COMPANY_NM 	VARCHAR(255),
	CARD_PAY_MONTH 		VARCHAR(255),
    PAY_ORDER_TIME 		TIMESTAMP				
);


CREATE TABLE CART (
	CART_ID   	   BIGINT AUTO_INCREMENT PRIMARY KEY,
	MEMBER_ID 	   VARCHAR(255),					# NOT NULL
	BOOK_ID  	   BIGINT,							# NOT NULL
	CART_BOOK_QTY  INT,								# NOT NULL
	ENROLL_DT 	   TIMESTAMP						# NOT NULL
);


CREATE TABLE CONTACT (
	CONTACT_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME		VARCHAR(255),					# NOT NULL			
	EMAIL		VARCHAR(255),					# NOT NULL
	SUBJECT		VARCHAR(255),					# NOT NULL
	CONTENT		VARCHAR(255),					# NOT NULL
	REG_DT  	TIMESTAMP						# NOT NULL
);

